# Generated by Django 2.1 on 2019-11-20 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lichthicong'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietThiCong',
            fields=[
                ('ngaycapnhat', models.DateField(auto_created=True)),
                ('macttc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghichu', models.CharField(blank=True, max_length=255, null=True)),
                ('hinhthucthicong', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hinh_thuc_thi_cong', to='accounts.Hinhthucthicong')),
                ('lichthicong', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lich_thi_cong', to='accounts.LichThiCong')),
                ('objectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectid_cx_cua_thi_cong', to='accounts.Cayxanh')),
                ('taikhoan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nguoi_dung_thi_cong_cong_trinh', to=settings.AUTH_USER_MODEL)),
                ('trangthaitc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trang_thai_cua_thi_cong', to='accounts.Trangthaitc')),
            ],
        ),
    ]
