# Generated by Django 2.1 on 2019-11-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191123_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietthicong',
            name='nhomthiconglich',
        ),
    ]
