# Generated by Django 2.1 on 2019-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chitietthicong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='duongdanavatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
