# Generated by Django 2.1 on 2019-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_chitietthicong_nhomthiconglich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietthicong',
            name='objectidcx',
        ),
        migrations.AddField(
            model_name='chitietthicong',
            name='nhomthiconglich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nhomthiconglich', to='accounts.NhomThiCong'),
        ),
    ]
