# Generated by Django 2.1.10 on 2019-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cayxanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tencx',
            fields=[
                ('matencx', models.CharField(db_column='MaTenCX', max_length=10, primary_key=True, serialize=False)),
                ('tencx', models.CharField(blank=True, db_column='TenCX', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TenCX',
                'managed': False,
            },
        ),
    ]
