# Generated by Django 2.1 on 2019-11-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191123_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chucnang',
            fields=[
                ('machucnang', models.AutoField(primary_key=True, serialize=False)),
                ('tenchucnang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chucnangnguoidung',
            fields=[
                ('machucnangnguoidung', models.AutoField(primary_key=True, serialize=False)),
                ('xem', models.CharField(blank=True, max_length=100, null=True)),
                ('them', models.CharField(blank=True, max_length=100, null=True)),
                ('sua', models.CharField(blank=True, max_length=100, null=True)),
                ('xoa', models.CharField(blank=True, max_length=100, null=True)),
                ('xuat', models.CharField(blank=True, max_length=100, null=True)),
                ('machucnang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Chucnang')),
            ],
        ),
        migrations.CreateModel(
            name='Quyennguoidung',
            fields=[
                ('maquyen', models.AutoField(primary_key=True, serialize=False)),
                ('quyennguoidung', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chucnangnguoidung',
            name='maquyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Quyennguoidung'),
        ),
    ]
