# Generated by Django 2.1.10 on 2019-07-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tencx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trangthaicx',
            fields=[
                ('matinhtrang', models.IntegerField(db_column='MaTinhTrang', primary_key=True, serialize=False)),
                ('tinhtrang', models.CharField(blank=True, db_column='TinhTrang', max_length=255, null=True)),
                ('ghichu', models.TextField(blank=True, db_column='GhiChu', null=True)),
            ],
            options={
                'db_table': 'TrangThaiCX',
                'managed': False,
            },
        ),
    ]
