# Generated by Django 2.1 on 2019-11-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191123_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chucnang',
            old_name='tenchucnang',
            new_name='chucnang',
        ),
    ]
