# Generated by Django 2.1.10 on 2019-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_trangthaicx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hinhthucthicong',
            fields=[
                ('maloai', models.CharField(db_column='MaLoai', max_length=10, primary_key=True, serialize=False)),
                ('tenloai', models.CharField(blank=True, db_column='TenLoai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'HinhThucThiCong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phuongxa',
            fields=[
                ('objectid', models.IntegerField(db_column='OBJECTID', primary_key=True, serialize=False)),
                ('tenphuongxa', models.CharField(blank=True, db_column='TenPhuongXa', max_length=254, null=True)),
                ('maquanhuyen', models.CharField(blank=True, db_column='MaQuanHuyen', max_length=20, null=True)),
                ('maphuongxa', models.CharField(blank=True, db_column='MaPhuongXa', max_length=20, null=True)),
                ('loai', models.CharField(blank=True, db_column='Loai', max_length=20, null=True)),
                ('tenkhongdau', models.CharField(blank=True, db_column='TenKhongDau', max_length=50, null=True)),
                ('shape', models.TextField(blank=True, db_column='Shape', null=True)),
            ],
            options={
                'db_table': 'PHUONGXA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quanhuyen',
            fields=[
                ('objectid', models.IntegerField(db_column='OBJECTID', primary_key=True, serialize=False)),
                ('maquanhuyen', models.CharField(blank=True, db_column='MaQuanHuyen', max_length=20, null=True)),
                ('tenquanhuyen', models.CharField(blank=True, db_column='TenQuanHuyen', max_length=20, null=True)),
                ('matinh', models.CharField(blank=True, db_column='MaTinh', max_length=12, null=True)),
                ('loai', models.CharField(blank=True, db_column='Loai', max_length=20, null=True)),
                ('tenkhongdau', models.CharField(blank=True, db_column='TenKhongDau', max_length=20, null=True)),
                ('shape', models.TextField(blank=True, db_column='Shape', null=True)),
            ],
            options={
                'db_table': 'QUANHUYEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timduong',
            fields=[
                ('objectid', models.IntegerField(db_column='OBJECTID', primary_key=True, serialize=False)),
                ('maduong', models.CharField(blank=True, db_column='MaDuong', max_length=50, null=True)),
                ('tenduong', models.CharField(blank=True, db_column='TenDuong', max_length=500, null=True)),
                ('shape', models.TextField(blank=True, db_column='SHAPE', null=True)),
            ],
            options={
                'db_table': 'TIMDUONG',
                'managed': False,
            },
        ),
    ]
