# Generated by Django 2.1.10 on 2019-09-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hinhthucthicong_phuongxa_quanhuyen_timduong'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='middlename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
