# Generated by Django 2.1 on 2019-11-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191123_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hinhanhcayxanh',
            options={},
        ),
    ]
