# Generated by Django 2.1 on 2019-11-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191124_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hinhanhcayxanh',
            options={'managed': False},
        ),
    ]
