# Generated by Django 2.1.10 on 2019-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190913_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
