# Generated by Django 2.1 on 2019-11-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191124_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietthicong',
            name='objectid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ob_cayxanh', to='accounts.Cayxanh'),
        ),
    ]
