# Generated by Django 2.1.10 on 2019-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191111_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
