# Generated by Django 2.1 on 2019-11-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191124_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='objectid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='sua',
            field=models.CharField(blank=True, default='1.0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='them',
            field=models.CharField(blank=True, default='1.0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xem',
            field=models.CharField(blank=True, default='1.0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xoa',
            field=models.CharField(blank=True, default='1.0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xuat',
            field=models.CharField(blank=True, default='1.0', max_length=100, null=True),
        ),
    ]
