# Generated by Django 2.1.10 on 2019-11-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191111_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
