# Generated by Django 2.1 on 2019-11-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191125_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='tuyenduong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuyenduongthicong', to='accounts.Timduong'),
        ),
    ]
