# Generated by Django 2.1 on 2019-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191125_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='ngaycapnhat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chitietthicong',
            name='tuyenduong',
            field=models.CharField(max_length=100),
        ),
    ]
