# Generated by Django 2.1 on 2019-11-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191126_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chucnang',
            fields=[
                ('machucnang', models.IntegerField(primary_key=True, serialize=False)),
                ('chucnang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quyennguoidung',
            fields=[
                ('maquyen', models.IntegerField(primary_key=True, serialize=False)),
                ('quyennguoidung', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chucnangnguoidung',
            name='machucnang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chuc_nang_nguoi_dung', to='accounts.Chucnang'),
        ),
        migrations.AddField(
            model_name='chucnangnguoidung',
            name='maquyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quyen_nguoi_dung', to='accounts.Quyennguoidung'),
        ),
    ]
