# Generated by Django 2.1 on 2019-11-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191126_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='quyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quyen', to='accounts.Quyennguoidung'),
        ),
    ]
