# Generated by Django 2.1 on 2019-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_myuser_quyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='sua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='them',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xoa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chucnangnguoidung',
            name='xuat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
