# Generated by Django 2.1 on 2019-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20191128_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgayThiCong',
            fields=[
                ('mangaytc', models.AutoField(primary_key=True, serialize=False)),
                ('NgayBD', models.DateField(auto_now=True)),
                ('NgayHoanThanh', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chitietthicong',
            name='NgayBD',
        ),
        migrations.RemoveField(
            model_name='chitietthicong',
            name='NgayHoanThanh',
        ),
    ]
