# Generated by Django 2.1 on 2019-11-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191128_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietthicong',
            name='ngaythicong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngaythicong', to='accounts.NgayThiCong'),
        ),
    ]
