# Generated by Django 2.1 on 2019-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_chitietthicong_ngaythicong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='lichthicong',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='LichThiCong',
        ),
    ]
