# Generated by Django 2.1 on 2019-11-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20191128_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietthicong',
            name='ngaythicong',
        ),
        migrations.AddField(
            model_name='chitietthicong',
            name='NgayBD',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chitietthicong',
            name='NgayHoanThanh',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='NgayThiCong',
        ),
    ]
