# Generated by Django 2.1 on 2019-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20191128_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='NgayBD',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chitietthicong',
            name='NgayHoanThanh',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='duongdanavatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
