# Generated by Django 2.1 on 2019-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20191128_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='ngaycapnhat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chitietthicong',
            name='tuyenduong',
            field=models.IntegerField(),
        ),
    ]
