# Generated by Django 2.1 on 2019-12-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20191210_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietthicong',
            name='tuyenduong',
            field=models.CharField(max_length=100),
        ),
    ]
